language: node_js
node_js:
  - "10.15"
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "noraui"

branches:
  only:
  - master

before_script:
  - export NG_CLI_ANALYTICS=ci
  - npm install -g angular-cli-ghpages
  - npm install -g @angular/cli
  - ng analytics off
  - npm install

script:
  - cd bakery-front
  - npm install
  - npm run lint
  - echo "***** START ANGULAR APPLICATION"
  - npm start &
  - sleep 120
  - echo "***** CURL to home url"
  - curl -s http://localhost:4200
  - npm run build
  - ngh --dir=dist/bakery --message="deploy by Travis-ci" --repo=https://$GITHUB_TOKEN@github.com/NoraUi/bakery.io.git --branch=master
