language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - cd bakery-front
  - npm install -g @angular/cli
script:
- npm run lint
- npm run build --base-href https://github.com/NoraUi/noraui.github.io/bakery/
