language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "noraui"

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli -s
  - ng analytics off
  - npm install

script:
  - cd bakery-front
  - npm install
  - npm run lint
  - echo "***** START ANGULAR APPLICATION"
  - npm start &
  - sleep 120
  - echo "***** CURL to home url"
  - curl -s http://localhost:4200
  - npm run build
  - ngh
